from typing import Optional

from PyQt6.QtCore import QRectF, QSize, Qt
from PyQt6.QtGui import QImage, QPainter
from PyQt6.QtWidgets import QGraphicsItem, QStyleOptionGraphicsItem, QWidget

THUMBNAIL_SIZE = QSize(32, 32)
"""The standard size for thumbnails generated by AIEImageItem."""


class AIEImageItem(QGraphicsItem):
    """
    Represents an image item in the AIEGraphicsScene.

    This item displays a QImage and allows it to be selected and moved
    within the scene. It provides a thumbnail for display in layer views
    and defines its bounding rectangle based on the image dimensions.
    """

    def __init__(self, image: QImage, name: str) -> None:
        """
        Initializes an AIEImageItem.

        Args:
            image: The QImage to display.
            name: The name of the image item, used for display in the layer tree.
        """
        super().__init__()
        self.name = name
        self.image = image
        self.setFlag(QGraphicsItem.GraphicsItemFlag.ItemIsSelectable, True)
        self.setFlag(QGraphicsItem.GraphicsItemFlag.ItemIsMovable, True)

    def get_thumbnail(self) -> QImage:
        """
        Generates a thumbnail version of the item's image.

        The thumbnail is scaled to `THUMBNAIL_SIZE` while maintaining aspect ratio.

        Returns:
            A QImage representing the thumbnail.
        """
        return self.image.scaled(
            THUMBNAIL_SIZE,
            Qt.AspectRatioMode.KeepAspectRatio,
            Qt.TransformationMode.SmoothTransformation,
        )

    def get_size_hint(self) -> QSize:
        """
        Returns the recommended size for this item's thumbnail.

        Returns:
            The standard `THUMBNAIL_SIZE`.
        """
        return THUMBNAIL_SIZE

    def boundingRect(self) -> QRectF:
        """
        Returns the bounding rectangle of this image item.

        The bounding rectangle is determined by the dimensions of the QImage.

        Returns:
            A QRectF representing the image's boundaries.
        """
        return QRectF(self.image.rect())

    def paint(
        self,
        painter: QPainter,
        option: QStyleOptionGraphicsItem,
        widget: Optional[QWidget] = None,
    ) -> None:
        """
        Paints the image item onto the scene.

        Args:
            painter: The QPainter to use for drawing.
            option: Provides style options for the item (unused).
            widget: The widget that is being painted on (unused).
        """
        painter.drawImage(self.boundingRect(), self.image)

    def setOpacity(self, opacity: float) -> None:
        """
        Sets the opacity of the image item.

        Args:
            opacity: The new opacity, from 0.0 (transparent) to 1.0 (opaque).
        """
        super().setOpacity(opacity) # Calls QGraphicsItem.setOpacity

    def opacity(self) -> float:
        """
        Returns the current opacity of the image item.

        Returns:
            The current opacity, from 0.0 (transparent) to 1.0 (opaque).
        """
        return super().opacity() # Calls QGraphicsItem.opacity
